// Generated by CoffeeScript 1.9.1
(function() {
  var _lazylayout, action, current, doAction, handle, handlers, updated,
    slice = [].slice;

  _lazylayout = require('./view')._lazylayout;

  handlers = {};

  handle = function(name, handler) {
    return handlers[name] = handler;
  };

  current = null;

  updated = {};

  action = function() {
    var as, name;
    name = arguments[0], as = 2 <= arguments.length ? slice.call(arguments, 1) : [];
    return doAction(name, as);
  };

  updated = function(name) {
    var qname;
    qname = "update:" + name;
    if (!current) {
      throw new Error("Rejected (" + qname + ") outside action");
    }
    if (!updated) {
      throw new Error("Rejected (" + qname + ") during updates for: " + current);
    }
    updated[qname] = true;
    return void 0;
  };

  doAction = function(name, as) {
    var _updated, qname;
    if (current) {
      throw new Error("Rejected (" + name + ") during action: " + current);
    }
    try {
      current = name;
      _lazylayout(true);
      return typeof handlers[name] === "function" ? handlers[name].apply(handlers, as) : void 0;
    } finally {
      _updated = updated;
      updated = null;
      try {
        for (qname in _updated) {
          if (typeof handlers[qname] === "function") {
            handlers[qname]();
          }
        }
      } finally {
        updated = {};
        current = null;
        _lazylayout(false);
      }
    }
  };

  module.exports = {
    handle: handle,
    action: action,
    updated: updated
  };

}).call(this);
