// Generated by CoffeeScript 1.10.0
(function() {
  var I, OrderedMap, builtin, concat, expose, indexof, mixin, select, startswith,
    slice = [].slice;

  I = function(a) {
    return a;
  };

  builtin = I.bind.bind(I.call);

  startswith = function(s, i) {
    return s.slice(0, i.length) === i;
  };

  indexof = builtin(String.prototype.indexOf);

  concat = function() {
    var as, ref;
    as = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    return (ref = []).concat.apply(ref, as);
  };

  mixin = function() {
    var j, k, len, o, os, r, v;
    os = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    r = {};
    for (j = 0, len = os.length; j < len; j++) {
      o = os[j];
      for (k in o) {
        v = o[k];
        r[k] = v;
      }
    }
    return r;
  };

  select = function(node, sel) {
    var doc;
    if (!node.parentNode) {
      doc = node.ownerDocument;
    }
    try {
      if (doc) {
        doc.body.appendChild(node);
      }
      switch (sel[0]) {
        case '.':
          return node.getElementsByClassName(sel.slice(1));
        case '#':
          return node.getElementById(sel.slice(1));
        default:
          return node.getElementsByTagName(sel);
      }
    } finally {
      if (doc) {
        doc.body.removeChild(node);
      }
    }
  };

  OrderedMap = (function() {
    function OrderedMap() {
      this.order = [];
      this.map = {};
    }

    OrderedMap.prototype.set = function(k, v) {
      if (!this.map.hasOwnProperty(k)) {
        this.order.push(k);
      }
      return this.map[k] = v;
    };

    OrderedMap.prototype.get = function(k) {
      return this.map[k];
    };

    return OrderedMap;

  })();

  expose = (function() {
    return function(exp, guard) {
      return function() {
        var as, fns, ks, obj, ofexp, props, valid;
        obj = arguments[0], as = 2 <= arguments.length ? slice.call(arguments, 1) : [];
        if (obj[guard]) {
          return;
        }
        ofexp = partial(get, exp);
        valid = function(as) {
          return map(as, function(a) {
            if (ofexp(a)) {
              return a;
            } else {
              throw "Not found: " + a;
            }
          });
        };
        ks = as.length ? valid(as) : keys(exp);
        fns = map(ofexp)(ks);
        props = zipobj(ks, map(asprop)(fns));
        Object.defineProperties(obj, props);
        Object.defineProperty(obj, guard, asprop(I));
        return exp;
      };
    };
  })();

  module.exports = {
    startswith: startswith,
    indexof: indexof,
    select: select,
    concat: concat,
    mixin: mixin,
    OrderedMap: OrderedMap,
    expose: expose
  };

}).call(this);
