// Generated by CoffeeScript 1.9.0
(function() {
  var OrderedMap, VDOMOut, capture, create, detach, diff, div, glob, layout, lcount, patch, region, select, view, walk, _lazy, _lazylayout, _ref, _ref1, _ref2,
    __slice = [].slice;

  _ref = require('virtual-dom'), diff = _ref.diff, patch = _ref.patch, create = _ref.create;

  _ref1 = require('tagg'), capture = _ref1.capture, div = _ref1.div;

  _ref2 = require('./fun'), select = _ref2.select, OrderedMap = _ref2.OrderedMap;

  VDOMOut = require('./vdomout');

  glob = null;

  glob = global || window;

  view = function(f) {
    var render;
    render = function() {
      var as, ptch, vt;
      as = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      vt = capture(new VDOMOut(), f, as);
      ptch = diff(render._vt, vt);
      render.el = patch(render.el, ptch);
      render._vt = vt;
      return render.el;
    };
    render.el = create((render._vt = capture(new VDOMOut(), div)), {
      document: glob.document
    });
    return render;
  };

  detach = function(view) {
    var _ref3, _ref4;
    if (!view) {
      return;
    }
    delete view._rg;
    return view != null ? (_ref3 = view.el) != null ? (_ref4 = _ref3.parentNode) != null ? _ref4.removeChild(view.el) : void 0 : void 0 : void 0;
  };

  region = function(n) {
    return {
      "data-region": n
    };
  };

  walk = function(node, f) {
    var c, _i, _len, _ref3, _results;
    f(node);
    _ref3 = node.childNodes;
    _results = [];
    for (_i = 0, _len = _ref3.length; _i < _len; _i++) {
      c = _ref3[_i];
      _results.push(walk(c, f));
    }
    return _results;
  };

  _lazy = null;

  lcount = 0;

  layout = function(f) {
    var inner, lid, makeRegionFunctions, regions, render;
    lid = lcount++;
    regions = {};
    inner = view(f);
    render = function() {
      var as, name, prevRegions, vw;
      as = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      if (_lazy) {
        throw new Error("Refusing to render layout when lazy evaluating");
      }
      try {
        for (name in regions) {
          vw = regions[name];
          if (vw) {
            detach(vw);
          }
        }
        return inner.apply(null, as);
      } finally {
        render.el = inner.el;
        prevRegions = regions;
        makeRegionFunctions();
        for (name in prevRegions) {
          vw = prevRegions[name];
          if (vw) {
            if (typeof render[name] === "function") {
              render[name](vw);
            }
          }
        }
      }
    };
    makeRegionFunctions = function() {
      regions = {};
      return walk(render.el, function(node) {
        var name, rg, _ref3;
        name = (_ref3 = node.dataset) != null ? _ref3.region : void 0;
        if (!name) {
          return;
        }
        regions[name] = false;
        return render[name] = rg = function(vw) {
          var prev, _ref4, _ref5;
          if (_lazy) {
            return _lazy.set(lid + ":" + name, (function() {
              return rg(vw);
            }));
          }
          if (((_ref4 = (prev = regions[name])) != null ? (_ref5 = _ref4.el) != null ? _ref5.parentNode : void 0 : void 0) != null) {
            detach(prev);
          }
          if (vw) {
            if (vw._rg) {
              vw._rg(null);
            }
            regions[name] = vw;
            node.appendChild(vw.el);
            return vw._rg = render[name];
          } else {
            return delete regions[name];
          }
        };
      });
    };
    render();
    return render;
  };

  _lazylayout = function(suspend) {
    var k, l, _i, _len, _ref3, _results;
    if (suspend) {
      if (!_lazy) {
        return _lazy = new OrderedMap();
      }
    } else if (_lazy) {
      l = _lazy;
      _lazy = null;
      _ref3 = l.order;
      _results = [];
      for (_i = 0, _len = _ref3.length; _i < _len; _i++) {
        k = _ref3[_i];
        _results.push(l.get(k)());
      }
      return _results;
    }
  };

  module.exports = {
    view: view,
    layout: layout,
    region: region,
    _lazylayout: _lazylayout
  };

}).call(this);
